### ISSUE TITLE
Focus Stealing

### ISSUE THREAD

**Issue by apparle** [lxieyang/vertical-tabs-chrome-extension#16]
Right now, the extensions "search tab here" steals focus from the website. For example, without this extension, if I open http://www.google.com , the default focus(cursor) is on the Google's search-box and I can just type and press enter. But after installing this extension, the side-bar appears a little late and steals the focus away from the page, so I've to first click on Google's textbox and then type in it.
Can this be fixed such that focus stays wherever it is on the webpage ?

**Comment by lxieyang** [comment]
Sure, will look into it!

**Comment by lxieyang** [comment]
This has been fixed in v1.2.1. Please expect the chrome store update in approximately 10 days. Thanks!
