### ISSUE TITLE
Unexpected Behaviour

### ISSUE THREAD

**Issue by smaragdus** [lxieyang/vertical-tabs-chrome-extension#22]
When I opened [this page](https://app.tryzulu.com/privacy.html) **Vertical Tabs** version **1.6.0** opened by itself and the pop-up window cannot be closed without closing the tab. Screen:

![Vertical Tabs 1 6 0 - 2020-01-15 - 003](https://user-images.githubusercontent.com/9025757/72392885-db4ad700-3739-11ea-96c3-ff02be01e99e.png)

This is very strange- I have been using [Vertical Tabs](https://github.com/lxieyang/vertical-tabs-chrome-extension) for several days and as far as can remember this problem did not happen on other pages. I am using [Vertical Tabs](https://chrome.google.com/webstore/detail/vertical-tabs/pddljdmihkpdfpkgmbhdomeeifpklgnm) with [Cent Browser](https://www.centbrowser.com/) version **4.1.7.182** on WIndows 8 x64.

Can you confirm this problem?

**Comment by lxieyang** [comment]
Yes, I'm seeing the same thing on my end. Unfortunately, I don't think it's something that can be fixed without affecting the original website. As far as I can see, the website is written in a way that puts a huge `margin` to the `<body>` tag to center align its content, which is something normal programmers wouldn't do (at least I'd use css flexbox). This is exactly what's causing the current issue.
That said, I'll try to find a fix anyways. If I do, I'll make sure to release a new version on the Chrome Web Store.
Thanks for trying out Vertical Tabs! Really appreciate it!

**Comment by smaragdus** [comment]
@lxieyang 

Thank you for your quick and explanatory response. Actually I don't care for this issue that much as it is unlikely that I will ever visit this page again. As I encountered it I felt obliged to report it. You may close this issue as it is isolated and insignificant.

I installed Vertical Tabs 4 days ago and I really like it. In am using your extensions along with several similar ones and I may suggest some features if you don't mind.

By the way the eyes on the tool bar button are very cute.

Regards

**Comment by lxieyang** [comment]
Thank you!! That meant the world to me and just made my day!
Please feel free to suggest new features (feel free to open up new issues :-))!
