### ISSUE TITLE
iframe-background.gif (question)

### ISSUE THREAD

**Issue by smaragdus** [lxieyang/vertical-tabs-chrome-extension#23]
Hello,

When I use **Image Downloader Continued** ([Chrome Web Store](https://chrome.google.com/webstore/detail/image-downloader-continue/jfkjbfhcfaoldhgbnkekkoheganchiea), [GitHub](https://github.com/kisdma/image-downloader-cnt)), an extension which extracts all image files found in a web page, it also gets a GIF file:

`iframe-background.gif`

which turned out to be a part of [Vertical Tabs](https://github.com/lxieyang/vertical-tabs-chrome-extension) extension, screen:

![Image Downloader Continued 2 8 - 2020-01-20 - 003](https://user-images.githubusercontent.com/9025757/72692873-f43afa00-3b36-11ea-9cb5-01df5b51ba54.png)

This file appears every time I extract images using **Image Downloader Continued** and I find this a bit annoying. Can you confirm this? Is there any workaround? Is this file (**iframe-background.gif**) needed for [Vertical Tabs](https://chrome.google.com/webstore/detail/vertical-tabs/pddljdmihkpdfpkgmbhdomeeifpklgnm) to function properly?

**Comment by lxieyang** [comment]
Hi, thanks for reporting the issue! A fix has been implemented and pushed to the Chrome Web Store. Please expect an update in about a week.

Also, thanks so much for trying this extension out! It really means the world to me!

**Comment by smaragdus** [comment]
@lxieyang 

Thank you for the extremely quick response and fix! You are very helpful as usual!

I have several ideas for possible enhancements but before suggesting anything I would like to know whether you would like to keep your extension as simple as possible or you don't mind adding new features? Also- which would be better- to suggest ideas in separate issues or in a single issue?

Regards

**Comment by lxieyang** [comment]
Please feel free to open up separate issues describing your ideas! My original intention was to keep the extension as a minimalistic one. However, my current thoughts are:
- add interesting and useful new features 
- give the users control in terms of what are the features they would like to enable in the settings menu
Therefore, please don't hesitate to contribute new ideas and I'll do my best to access them and make them happen asap!

**Comment by lxieyang** [comment]
@smaragdus v1.6.1 is live on the Chrome Web Store. Please update and see if the bug has been fixed. Thanks!

**Comment by smaragdus** [comment]
@lxieyang 

I got version **1.6.1** of [Vertical Tabs](https://github.com/lxieyang/vertical-tabs-chrome-extension) through [Chrome Web Store](https://chrome.google.com/webstore/detail/vertical-tabs/pddljdmihkpdfpkgmbhdomeeifpklgnm) and I can confirm that the file I mentioned above (`iframe-background.gif`) no longer appears in the extracted images, thank you!
