### ISSUE TITLE
Context Menu Command - Copy Tab URL

### ISSUE THREAD

**Issue by smaragdus** [lxieyang/vertical-tabs-chrome-extension#24]
I would like to suggest a tiny enhancement- a new context menu command:

- **Copy Tab URL**

There are lots of copy URL extensions, some of them are very powerful (supporting copying of multiple tabs, HTML, MD, BBCode, LaTeX, etc) and I use several. Yet I think that adding such new context menu command to [Vertical Tabs](https://github.com/lxieyang/vertical-tabs-chrome-extension) is natural. It would be especially useful to users who don't use dedicated copy URL extensions.

The context menu command may be named **Copy Tab URL** or just **Copy URL**, you decide.

**Comment by lxieyang** [comment]
Hi, the feature has been added in [v1.7.0](https://github.com/lxieyang/vertical-tabs-chrome-extension/releases/tag/v1.7.0). I've also pushed an update to the Chrome Web Store, so hopefully you'll get it in a few days :-).

<img width="150" alt="context-menu-with-icons" src="https://user-images.githubusercontent.com/16089305/73043207-2fd50d00-3e32-11ea-8d2c-03c89ed2f1e4.png">

**Comment by smaragdus** [comment]
@lxieyang 

You speed never stops to amaze me! The new context command looks nice and just exactly as I have imagined it. I also see that you have iconized the commands, this is also a good idea.

I hope that you find 'Copy Tab Url' command useful.

I may suggest some other features these days but please be aware that I never expect all my suggestions to be implemented. So if it happens that you don't like any of my suggestions or they are not congruent with the initial design of the extension, feel free to discard them.

I wish more developers were as quick, helpful and responsive as you- I have opened issues that haven't been responded for years. ;)

In the meantime you may close this issue, I will close it myself when I get the update via the store.

Regards

**Comment by lxieyang** [comment]
v1.7.1 is live.

**Comment by smaragdus** [comment]
@lxieyang 

> v1.7.1 is live.

Yes, I got [version](https://github.com/lxieyang/vertical-tabs-chrome-extension/releases) [1.7.1](https://github.com/lxieyang/vertical-tabs-chrome-extension/releases/tag/v1.7.1) via [Chrome Web Store](https://chrome.google.com/webstore/detail/vertical-tabs/pddljdmihkpdfpkgmbhdomeeifpklgnm) and as everything is working fine I am closing this issue, thank you.
