### ISSUE TITLE
Unexpected tab close

### ISSUE THREAD

**Issue by PeiyuanQi** [lxieyang/vertical-tabs-chrome-extension#26]
If you got 2 windows and completely close all tabs in this window, the other window's current tab will be closed.

**Comment by lxieyang** [comment]
hmm, that's interesting! I'll look into it!

**Comment by PeiyuanQi** [comment]
more detailed scenario:
window 1 opens and running sidebar with many tabes. 
another window only opens google hangout.
cmd+w close hangout chat, hangout chat window does not disappear as usual.
click on close of hangout window, also results in the tab in window 1 closed.

This problem does not exist before Vertical Tabs installed.

but it has a limited case to reproduce maybe not a big issue.

**Comment by lxieyang** [comment]
Thanks for reporting the issue and providing a reproducible case! I'll look into it!

**Comment by PeiyuanQi** [comment]
after disabling the plugin, this problem is still there, so I think the problem is not from the plugin, but chrome... so maybe is not a proper repo to create this issue.
