### ISSUE TITLE
Port to safari

### ISSUE THREAD

**Issue by wangfenjin** [lxieyang/vertical-tabs-chrome-extension#61]
Hi, I plan to port this extension to support safari, and publish to App Store. Is that OK?

**Comment by lxieyang** [comment]
Sure! I wouldn't have the bandwidth to do it anyway :-) 
Would you please loop me in on the progress and the results? Thanks!

**Comment by wangfenjin** [comment]
Currently the extension is quite working now, but I haven’t publish any extension before, so first need to become an apple developer

And I plan to sell it for several dollars since registering apple developer cost money...

**Comment by wangfenjin** [comment]
Do you prefer to make it free available?

**Comment by lxieyang** [comment]
I would insist on it being freely available like the chrome version :-) 
I too paid to become a Chrome developer and an Apple developer, but those were one-time costs that become relatively insignificant in the long run :-)

**Comment by wangfenjin** [comment]
Sure! Maybe we can make it free in the beginning so all currently users can access to it and change to paid after that

**Comment by lxieyang** [comment]
Sounds good! Thanks for the effort!
Another idea is to set up donations through Paypal or Patreon. A lot of open-source software are being supported in this way.

**Comment by wangfenjin** [comment]
@lxieyang It's online now!

https://apps.apple.com/us/app/vertical-tabs-for-safari/id1552657113?mt=12&itsct=apps_box&itscg=30200

**Comment by wangfenjin** [comment]
For the difference, rearrange tab order is not supported in safari; and message listener seems not work in iframes in safari, so I set a Interval to query to tabs...

**Comment by lxieyang** [comment]
Sounds good! Congrats!!
